# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_book_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditTitle = QtWidgets.QLineEdit(Dialog)
        self.lineEditTitle.setGeometry(QtCore.QRect(150, 40, 113, 20))
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.lineEditAuthor = QtWidgets.QLineEdit(Dialog)
        self.lineEditAuthor.setGeometry(QtCore.QRect(150, 80, 113, 20))
        self.lineEditAuthor.setObjectName("lineEditAuthor")
        self.lineEditYear = QtWidgets.QLineEdit(Dialog)
        self.lineEditYear.setGeometry(QtCore.QRect(150, 120, 113, 20))
        self.lineEditYear.setObjectName("lineEditYear")
        self.lineEditGenre = QtWidgets.QLineEdit(Dialog)
        self.lineEditGenre.setGeometry(QtCore.QRect(150, 160, 113, 20))
        self.lineEditGenre.setObjectName("lineEditGenre")
        self.lineEditCopies = QtWidgets.QLineEdit(Dialog)
        self.lineEditCopies.setGeometry(QtCore.QRect(150, 200, 113, 20))
        self.lineEditCopies.setObjectName("lineEditCopies")
        self.btnAddBook = QtWidgets.QPushButton(Dialog)
        self.btnAddBook.setGeometry(QtCore.QRect(170, 250, 75, 23))
        self.btnAddBook.setObjectName("btnAddBook")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 101, 16))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 47, 13))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 47, 13))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 111, 16))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnAddBook.setText(_translate("Dialog", "Добавить"))
        self.label.setText(_translate("Dialog", "Название книги"))
        self.label_2.setText(_translate("Dialog", "Автор"))
        self.label_3.setText(_translate("Dialog", "Год"))
        self.label_4.setText(_translate("Dialog", "Жанр"))
        self.label_5.setText(_translate("Dialog", "Кол-во экземпляров"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
